### ISSUE TITLE
[Feature] Ability to rename a book

### ISSUE THREAD

**Issue by deepanchal** [deepanchal/dnote-tui#15]
## Description

Add ability to rename a book when in books section.

### Tasks

- [ ] Add `r` keybinding to rename when in books section
- [ ] Show popup with text field with current notebook name prefilled
- [ ] Press `esc` on popup to cancel rename
- [ ] Press `enter` on popup to rename book
