### ISSUE TITLE
[Feature] Show truncated content beside page id in pages section

### ISSUE THREAD

**Issue by deepanchal** [deepanchal/dnote-tui#18]
## Description

Show truncated content beside page id in pages section

## Screenshots

N/A

## Tasks

- [ ] Add ability to store truncated page content in DnotePage struct
- [ ] Add tests for parsing string from stdout to DnotePage struct
- [ ] Use new field in tui to show truncated content
